USE DALTONS;

SELECT * FROM USER
JOIN ROLE
ON ROLE.ROLE_ID = USER.ROLE_ID
JOIN POST
ON POST.USER_ID = USER.USER_ID
JOIN PICTURE
ON PICTURE.POST_ID = POST.POST_ID
JOIN COMMENT
ON COMMENT.POST_ID = POST.POST_ID;